### ISSUE TITLE
Transfer to PhD Checklist

### ISSUE THREAD

**Issue by bankheak** [bankheak/Dolphins#1]
# Here are the steps to add a PhD degree

- [ ] Mauricio will need to send a letter of support explaining that 2 years of funding is available, and that he supports me continuing for a PhD after completing my MS with a few notes about how my doctoral research aligns with his work.
- [ ] Supply my updated CV and statement of purpose to Scarlett.
- [ ] Add at least one more committee member.
- [ ] Create a doctoral program of study within a few terms.
- [ ] Hold a new research review for my dissertation proposal.
- [ ] Complete the preliminary exams before I defend for PhD.
